#!/usr/bin/env python3
"""Add all missing i18n keys to tr.json and en.json"""
import json

# === New keys to add to TR ===
TR_NEW_KEYS = {
    # Composite HTML keys (data-i18n-html)
    "idx.cta.title": "Dönüşümün<br/><span class=\"gradient-text\">Zamanı Geldi.</span>",
    "kurs.hero.title": "İK Dönüşüm<br/><span class=\"gradient-text\">Akademisi</span>",
    "danis.hero.title": "İK ve Yönetim<br/><span class=\"gradient-text\">Değişimi Danışmanlığı</span>",
    "danis.section.title": "Kurumunuza Özel <span class=\"gradient-text\">Çözüm Alanları</span>",
    "danis.approach.title": "Stratejiyi Sunumdan <span class=\"gradient-text\">Sahaya İndiriyoruz</span>",
    "danis.cta.title": "Dönüşümünüzü<br/><span class=\"gradient-text\">Birlikte Tasarlayalım</span>",
    "danis.sectors.title": "Farklı Sektörlerde<br><span class=\"gradient-text\">Ortak Dönüşüm</span>",

    # aileden-kuruma.html CTA — html version
    "danis.aileden.cta.title2": "Kurumunuz için <span class=\"gradient-text\">özel çözüm</span> tasarlayalım",

    # Alias keys for danismanliklar pages using "2" suffix
    "danis.aileden.cta.desc2": "Her kurum farklıdır. Size özel yaklaşım, metodoloji ve uygulama planıyla yanınızdayız.",
    "shared.challenge.title2": "Sorun: Dönemin Gerçekleri",
    "shared.solution.title2": "Çözüm: Derin Akademi Yaklaşımı",
    "shared.process.label2": "Süreç",
    "shared.process.title2": "Nasıl Çalışıyoruz?",
    "shared.scope.title2": "Ne Kazanırsınız?",
    "shared.footer.brandesc2": "İnsan kaynakları alanında uzmanlaşmış danışmanlık ve eğitim şirketi. Anlatan değil, çalışan sistemler kurarız.",
    "shared.footer.brandesc1": "İnsan kaynakları alanında uzmanlaşmış danışmanlık ve eğitim şirketi. Anlatan değil, çalışan sistemler kurarız.",
    "shared.footer.gizlilik2": "Gizlilik Politikası",

    # Consulting detail page keys (category, subtitle)
    "danis.kadro.category": "Sistem & Yönetim",
    "danis.kadro.subtitle": "Kurumların büyüme hedeflerini destekleyen organizasyon yapısının ve insan kaynağı planlamasının oluşturulmasını sağlamak.",
    "danis.kadro.quote": "Doğru organizasyon yapısı, doğru insanları doğru yerlere konumlandırmanın temelidir.",
    # Steps
    "danis.kadro.step1.title": "Mevcut Yapı Analizi",
    "danis.kadro.step1.desc": "Şirketin 3-5 yıllık büyüme planı incelenerek işgücü etkileri belirlenir.",
    "danis.kadro.step2.title": "Rol Haritalama",
    "danis.kadro.step2.desc": "Tüm çalışanların yetkinlik, performans ve potansiyel değerlendirmesi yapılır.",
    "danis.kadro.step3.title": "Organizasyon Tasarımı",
    "danis.kadro.step3.desc": "Gelecek ihtiyaçlar ile mevcut kapasite arasındaki farklar belirlenir.",
    "danis.kadro.step4.title": "İş Gücü Planlaması",
    "danis.kadro.step4.desc": "İşe alım, eğitim, rotasyon ve dış tedarik stratejileri tasarlanır.",
    "danis.kadro.step5.title": "Uygulama Desteği",
    "danis.kadro.step5.desc": "Çeyreklik plan gözden geçirme ve yıllık strateji güncelleme mekanizması.",
    # Values
    "danis.kadro.val1.title": "Organizasyon Analizi",
    "danis.kadro.val1.desc": "Mevcut yapının güçlü ve zayıf yönlerinin tespiti",
    "danis.kadro.val2.title": "Yapı Tasarımı",
    "danis.kadro.val2.desc": "Strateji ile uyumlu organizasyon yapısı",
    "danis.kadro.val3.title": "İş Gücü Planlaması",
    "danis.kadro.val3.desc": "Doğru insan kaynağı planlaması",
    "danis.kadro.val4.title": "Kritik Roller",
    "danis.kadro.val4.desc": "Kritik pozisyonların belirlenmesi ve yönetimi",

    "danis.olc.category": "Sistem & Yönetim",
    "danis.olc.subtitle": "Organizasyonlarda bireysel ve ekip performansını kurum stratejisiyle uyumlu şekilde ölçen ve geliştiren sürdürülebilir bir performans yönetim sistemi kurmak.",
    "danis.olc.quote": "Performans yönetimi, form doldurmak değil, insanları geliştirmektir.",
    "danis.olc.step1.title": "Mevcut Sistem Analizi",
    "danis.olc.step1.desc": "Mevcut değerlendirme sürecinin güçlü ve zayıf yönleri analiz edilir.",
    "danis.olc.step2.title": "Model Tasarımı",
    "danis.olc.step2.desc": "OKR, MBO veya karma model; kuruma en uygun yaklaşım belirlenir.",
    "danis.olc.step3.title": "Hedef Yapısı",
    "danis.olc.step3.desc": "Yıllık döngü, check-in sıklığı ve değerlendirme aşamaları tasarlanır.",
    "danis.olc.step4.title": "Pilot Uygulama",
    "danis.olc.step4.desc": "Hedef belirleme formu, değerlendirme rubriği ve gelişim planı şablonu hazırlanır.",
    "danis.olc.step5.title": "Tam Uygulama",
    "danis.olc.step5.desc": "Sistemin hayata geçmesi için yönetici eğitimi ve koçluk desteği verilir.",
    "danis.olc.val1.title": "Performans Modeli",
    "danis.olc.val1.desc": "Strateji ile uyumlu performans sistemi",
    "danis.olc.val2.title": "Hedef ve KPI Yapısı",
    "danis.olc.val2.desc": "Net hedeflerle performans yönetimi",
    "danis.olc.val3.title": "Performans Görüşmeleri",
    "danis.olc.val3.desc": "Gelişim odaklı performans diyalogları",
    "danis.olc.val4.title": "Gelişim Planları",
    "danis.olc.val4.desc": "Performans sonuçlarından gelişim planlarına",

    "danis.guclen.category": "Veri Odaklı İK",
    "danis.guclen.subtitle": "İnsan kaynakları kararlarının veri ile desteklenmesini sağlayan analitik altyapıyı kurmak.",
    "danis.guclen.quote": "Ölçemediğiniz şeyi yönetemezsiniz.",
    "danis.guclen.step1.title": "Metrik Belirleme",
    "danis.guclen.step1.desc": "İK metrikleri ve göstergeleri belirlenir.",
    "danis.guclen.step2.title": "Veri Altyapısı",
    "danis.guclen.step2.desc": "Veri toplama ve analiz altyapısı kurulur.",
    "danis.guclen.step3.title": "Dashboard Tasarımı",
    "danis.guclen.step3.desc": "İK dashboardları tasarlanır ve oluşturulur.",
    "danis.guclen.step4.title": "Raporlama",
    "danis.guclen.step4.desc": "Yönetim raporları ve karar destek sistemi kurulur.",
    "danis.guclen.step5.title": "Eğitim ve Devir",
    "danis.guclen.step5.desc": "Ekibin sistemi kullanması için eğitim ve destek sağlanır.",
    "danis.guclen.val1.title": "İK Metrikleri",
    "danis.guclen.val1.desc": "Doğru metriklerin belirlenmesi ve takibi",
    "danis.guclen.val2.title": "Dashboard",
    "danis.guclen.val2.desc": "Görsel ve etkili İK raporlama",
    "danis.guclen.val3.title": "Veri Analizi",
    "danis.guclen.val3.desc": "Veriden içgörü üretme",
    "danis.guclen.val4.title": "Yönetim Raporları",
    "danis.guclen.val4.desc": "Güçlü karar destek sistemi",

    "danis.strateji.category": "Liderlik & Organizasyon Gelişimi",
    "danis.strateji.subtitle": "Kurumların uzun vadeli yönünü netleştiren vizyon ve misyonun oluşturulması, stratejik hedeflerin belirlenmesi ve bu hedeflerin organizasyon içinde anlaşılır ve uygulanabilir hale getirilmesi.",
    "danis.strateji.quote": "Net bir vizyon olmadan strateji, rotası olmayan bir gemidir.",
    "danis.strateji.step1.title": "Durum Analizi",
    "danis.strateji.step1.desc": "Mevcut vizyon, misyon ve stratejik belgeler incelenir.",
    "danis.strateji.step2.title": "Paydaş Görüşmeleri",
    "danis.strateji.step2.desc": "Yönetim ekibi ile derinlemesine mülakatlar yürütülür.",
    "danis.strateji.step3.title": "Çalıştaylar",
    "danis.strateji.step3.desc": "Vizyon, misyon ve stratejik hedefler birlikte belirlenir.",
    "danis.strateji.step4.title": "Belgelendirme",
    "danis.strateji.step4.desc": "Stratejik plan ve kurumsal değerler yazılı hale getirilir.",
    "danis.strateji.step5.title": "Uygulama Desteği",
    "danis.strateji.step5.desc": "Stratejilerin operasyonel hedeflere dönüştürülmesinde destek sağlanır.",
    "danis.strateji.val1.title": "Vizyon & Misyon",
    "danis.strateji.val1.desc": "Net kurumsal yön ve amaç belirleme",
    "danis.strateji.val2.title": "Stratejik Hedefler",
    "danis.strateji.val2.desc": "Organizasyon genelinde ortak hedefler",
    "danis.strateji.val3.title": "Kurumsal Değerler",
    "danis.strateji.val3.desc": "Kurum kültürünü yönlendiren ilkeler",
    "danis.strateji.val4.title": "Strateji Hizalama",
    "danis.strateji.val4.desc": "Stratejilerin operasyonel hedeflere dönüşmesi",

    "danis.ucret.category": "Sistem & Yönetim",
    "danis.ucret.subtitle": "Kurumlarda sürdürülebilir, adil ve rekabetçi bir ücret ve yan haklar sistemi oluşturarak çalışan bağlılığını ve organizasyon performansını desteklemek.",
    "danis.ucret.quote": "Adil ücret sistemi, çalışan bağlılığının temelidir.",
    "danis.ucret.step1.title": "Ücret Analizi",
    "danis.ucret.step1.desc": "Mevcut ücret yapısı ve piyasa karşılaştırması yapılır.",
    "danis.ucret.step2.title": "Bant Tasarımı",
    "danis.ucret.step2.desc": "Ücret bantları ve kademeler oluşturulur.",
    "danis.ucret.step3.title": "Prim Sistemi",
    "danis.ucret.step3.desc": "Prim ve teşvik mekanizmaları tasarlanır.",
    "danis.ucret.step4.title": "Toplam Ödül",
    "danis.ucret.step4.desc": "Toplam ödül yaklaşımı çerçevesi oluşturulur.",
    "danis.ucret.step5.title": "Uygulama Desteği",
    "danis.ucret.step5.desc": "Sistemin uygulanması ve dönemsel güncellemeler planlanır.",
    "danis.ucret.val1.title": "Ücret Bantları",
    "danis.ucret.val1.desc": "Adil ve rekabetçi ücret yapısı",
    "danis.ucret.val2.title": "Prim Sistemi",
    "danis.ucret.val2.desc": "Performansa dayalı teşvik mekanizmaları",
    "danis.ucret.val3.title": "Piyasa Analizi",
    "danis.ucret.val3.desc": "Sektörel ücret karşılaştırmaları",
    "danis.ucret.val4.title": "Toplam Ödül",
    "danis.ucret.val4.desc": "Bütünsel ödüllendirme yaklaşımı",

    "danis.yetenek.category": "Sistem & Yönetim",
    "danis.yetenek.subtitle": "Kurumların doğru yetenekleri çekmesini, geliştirmesini ve elde tutmasını sağlayan sistematik bir yetenek yönetimi yaklaşımı kurmak.",
    "danis.yetenek.quote": "Doğru yetenekleri çekmek kadar, onları geliştirmek ve elde tutmak da stratejik bir yaklaşım gerektirir.",
    "danis.yetenek.step1.title": "Mevcut Durum",
    "danis.yetenek.step1.desc": "İşe alım ve yetenek yönetimi süreçleri analiz edilir.",
    "danis.yetenek.step2.title": "Yetkinlik Modeli",
    "danis.yetenek.step2.desc": "Pozisyonlara özel yetkinlik modelleri oluşturulur.",
    "danis.yetenek.step3.title": "Süreç Tasarımı",
    "danis.yetenek.step3.desc": "İşe alım ve değerlendirme süreçleri yeniden tasarlanır.",
    "danis.yetenek.step4.title": "Yetenek Havuzu",
    "danis.yetenek.step4.desc": "Yetenek havuzu ve kariyer gelişim planları oluşturulur.",
    "danis.yetenek.step5.title": "Uygulama Desteği",
    "danis.yetenek.step5.desc": "Sistemin hayata geçirilmesi ve izlenmesi desteklenir.",
    "danis.yetenek.val1.title": "İşe Alım Süreci",
    "danis.yetenek.val1.desc": "Doğru yetenek seçimi için sistematik süreç",
    "danis.yetenek.val2.title": "Yetkinlik Modeli",
    "danis.yetenek.val2.desc": "Pozisyonlara özel yetkinlik çerçevesi",
    "danis.yetenek.val3.title": "Yetenek Havuzu",
    "danis.yetenek.val3.desc": "Sürdürülebilir yetenek pipeline'ı",
    "danis.yetenek.val4.title": "Kariyer Gelişimi",
    "danis.yetenek.val4.desc": "Çalışan gelişimini destekleyen kariyer yolakları",
}

# === New keys to add to EN ===
EN_NEW_KEYS = {
    "idx.cta.title": "Time for<br/><span class=\"gradient-text\">Transformation.</span>",
    "kurs.hero.title": "HR Transformation<br/><span class=\"gradient-text\">Academy</span>",
    "danis.hero.title": "HR & Management<br/><span class=\"gradient-text\">Transformation Consulting</span>",
    "danis.section.title": "Custom Solutions <span class=\"gradient-text\">For Your Institution</span>",
    "danis.approach.title": "From Presentations to <span class=\"gradient-text\">Real-World Execution</span>",
    "danis.cta.title": "Let's Design Your<br/><span class=\"gradient-text\">Transformation Together</span>",
    "danis.sectors.title": "Shared Transformation<br><span class=\"gradient-text\">Across Sectors</span>",
    "danis.aileden.cta.title2": "Let's Design a <span class=\"gradient-text\">Custom Solution</span> for Your Institution",
    "danis.aileden.cta.desc2": "Every institution is different. We are with you every step of the way with a customized approach, methodology, and implementation plan.",
    "shared.challenge.title2": "Challenge: Current Realities",
    "shared.solution.title2": "Solution: The Derin Akademi Approach",
    "shared.process.label2": "Process",
    "shared.process.title2": "How Do We Work?",
    "shared.scope.title2": "What Will You Gain?",
    "shared.footer.brandesc2": "A consulting and training company specializing in human resources. We build systems that work, not just present.",
    "shared.footer.brandesc1": "A consulting and training company specializing in human resources. We build systems that work, not just present.",
    "shared.footer.gizlilik2": "Privacy Policy",

    "danis.kadro.category": "Systems & Management",
    "danis.kadro.subtitle": "Establishing the organizational structure and human resource planning that supports institutions' growth targets.",
    "danis.kadro.quote": "The right organizational structure is the foundation for placing the right people in the right positions.",
    "danis.kadro.step1.title": "Current Structure Analysis",
    "danis.kadro.step1.desc": "The company's 3-5 year growth plan is reviewed to identify workforce impacts.",
    "danis.kadro.step2.title": "Role Mapping",
    "danis.kadro.step2.desc": "Competency, performance and potential assessments are made for all employees.",
    "danis.kadro.step3.title": "Organization Design",
    "danis.kadro.step3.desc": "Gaps between future needs and current capacity are identified.",
    "danis.kadro.step4.title": "Workforce Planning",
    "danis.kadro.step4.desc": "Recruitment, training, rotation and outsourcing strategies are designed.",
    "danis.kadro.step5.title": "Implementation Support",
    "danis.kadro.step5.desc": "Quarterly plan reviews and annual strategy update mechanisms.",
    "danis.kadro.val1.title": "Organization Analysis",
    "danis.kadro.val1.desc": "Identifying strengths and weaknesses of current structure",
    "danis.kadro.val2.title": "Structure Design",
    "danis.kadro.val2.desc": "Organizational structure aligned with strategy",
    "danis.kadro.val3.title": "Workforce Planning",
    "danis.kadro.val3.desc": "Accurate human resource planning",
    "danis.kadro.val4.title": "Critical Roles",
    "danis.kadro.val4.desc": "Identifying and managing critical positions",

    "danis.olc.category": "Systems & Management",
    "danis.olc.subtitle": "Establishing a sustainable performance management system that measures and develops individual and team performance in alignment with organizational strategy.",
    "danis.olc.quote": "Performance management is not filling out forms — it's developing people.",
    "danis.olc.step1.title": "Current System Analysis",
    "danis.olc.step1.desc": "Strengths and weaknesses of the current evaluation process are analyzed.",
    "danis.olc.step2.title": "Model Design",
    "danis.olc.step2.desc": "OKR, MBO or hybrid model; the best approach for your institution is determined.",
    "danis.olc.step3.title": "Goal Structure",
    "danis.olc.step3.desc": "Annual cycle, check-in frequency and evaluation phases are designed.",
    "danis.olc.step4.title": "Pilot Implementation",
    "danis.olc.step4.desc": "Goal-setting forms, evaluation rubrics and development plan templates are prepared.",
    "danis.olc.step5.title": "Full Rollout",
    "danis.olc.step5.desc": "Manager training and coaching support for going live.",
    "danis.olc.val1.title": "Performance Model",
    "danis.olc.val1.desc": "Performance system aligned with strategy",
    "danis.olc.val2.title": "Goals & KPI Structure",
    "danis.olc.val2.desc": "Performance management with clear objectives",
    "danis.olc.val3.title": "Performance Reviews",
    "danis.olc.val3.desc": "Development-focused performance dialogues",
    "danis.olc.val4.title": "Development Plans",
    "danis.olc.val4.desc": "From performance results to development plans",

    "danis.guclen.category": "Data-Driven HR",
    "danis.guclen.subtitle": "Building the analytics infrastructure that supports HR decisions with data.",
    "danis.guclen.quote": "You can't manage what you can't measure.",
    "danis.guclen.step1.title": "Metric Definition",
    "danis.guclen.step1.desc": "HR metrics and indicators are defined.",
    "danis.guclen.step2.title": "Data Infrastructure",
    "danis.guclen.step2.desc": "Data collection and analysis infrastructure is established.",
    "danis.guclen.step3.title": "Dashboard Design",
    "danis.guclen.step3.desc": "HR dashboards are designed and built.",
    "danis.guclen.step4.title": "Reporting",
    "danis.guclen.step4.desc": "Management reports and decision support system are established.",
    "danis.guclen.step5.title": "Training & Handover",
    "danis.guclen.step5.desc": "Training and support for the team to use the system.",
    "danis.guclen.val1.title": "HR Metrics",
    "danis.guclen.val1.desc": "Identifying and tracking the right metrics",
    "danis.guclen.val2.title": "Dashboard",
    "danis.guclen.val2.desc": "Visual and effective HR reporting",
    "danis.guclen.val3.title": "Data Analysis",
    "danis.guclen.val3.desc": "Generating insights from data",
    "danis.guclen.val4.title": "Management Reports",
    "danis.guclen.val4.desc": "Powerful decision support system",

    "danis.strateji.category": "Leadership & Organizational Development",
    "danis.strateji.subtitle": "Developing the vision and mission that clarifies institutions' long-term direction, defining strategic goals and making them understandable and actionable within the organization.",
    "danis.strateji.quote": "Without a clear vision, strategy is a ship without a course.",
    "danis.strateji.step1.title": "Situation Analysis",
    "danis.strateji.step1.desc": "Current vision, mission and strategic documents are reviewed.",
    "danis.strateji.step2.title": "Stakeholder Interviews",
    "danis.strateji.step2.desc": "In-depth interviews are conducted with the management team.",
    "danis.strateji.step3.title": "Workshops",
    "danis.strateji.step3.desc": "Vision, mission and strategic goals are defined together.",
    "danis.strateji.step4.title": "Documentation",
    "danis.strateji.step4.desc": "The strategic plan and institutional values are put in writing.",
    "danis.strateji.step5.title": "Implementation Support",
    "danis.strateji.step5.desc": "Support is provided in converting strategies into operational goals.",
    "danis.strateji.val1.title": "Vision & Mission",
    "danis.strateji.val1.desc": "Clear institutional direction and purpose",
    "danis.strateji.val2.title": "Strategic Goals",
    "danis.strateji.val2.desc": "Shared goals across the organization",
    "danis.strateji.val3.title": "Institutional Values",
    "danis.strateji.val3.desc": "Principles guiding corporate culture",
    "danis.strateji.val4.title": "Strategy Alignment",
    "danis.strateji.val4.desc": "Translating strategies into operational goals",

    "danis.ucret.category": "Systems & Management",
    "danis.ucret.subtitle": "Creating a sustainable, fair and competitive compensation and benefits system that supports employee engagement and organizational performance.",
    "danis.ucret.quote": "A fair compensation system is the foundation of employee engagement.",
    "danis.ucret.step1.title": "Compensation Analysis",
    "danis.ucret.step1.desc": "Current compensation structure and market benchmarking.",
    "danis.ucret.step2.title": "Band Design",
    "danis.ucret.step2.desc": "Compensation bands and grades are established.",
    "danis.ucret.step3.title": "Bonus System",
    "danis.ucret.step3.desc": "Bonus and incentive mechanisms are designed.",
    "danis.ucret.step4.title": "Total Reward",
    "danis.ucret.step4.desc": "Total reward approach framework is established.",
    "danis.ucret.step5.title": "Implementation Support",
    "danis.ucret.step5.desc": "System implementation and periodic updates are planned.",
    "danis.ucret.val1.title": "Compensation Bands",
    "danis.ucret.val1.desc": "Fair and competitive pay structure",
    "danis.ucret.val2.title": "Bonus System",
    "danis.ucret.val2.desc": "Performance-based incentive mechanisms",
    "danis.ucret.val3.title": "Market Analysis",
    "danis.ucret.val3.desc": "Sector-wide compensation benchmarks",
    "danis.ucret.val4.title": "Total Reward",
    "danis.ucret.val4.desc": "Holistic reward approach",

    "danis.yetenek.category": "Systems & Management",
    "danis.yetenek.subtitle": "Building a systematic talent management approach that enables institutions to attract, develop and retain the right talent.",
    "danis.yetenek.quote": "Attracting the right talent requires as much strategic effort as developing and retaining them.",
    "danis.yetenek.step1.title": "Current State",
    "danis.yetenek.step1.desc": "Recruitment and talent management processes are analyzed.",
    "danis.yetenek.step2.title": "Competency Model",
    "danis.yetenek.step2.desc": "Position-specific competency models are developed.",
    "danis.yetenek.step3.title": "Process Design",
    "danis.yetenek.step3.desc": "Recruitment and assessment processes are redesigned.",
    "danis.yetenek.step4.title": "Talent Pool",
    "danis.yetenek.step4.desc": "Talent pipelines and career development plans are created.",
    "danis.yetenek.step5.title": "Implementation Support",
    "danis.yetenek.step5.desc": "Launching and monitoring the system is supported.",
    "danis.yetenek.val1.title": "Recruitment Process",
    "danis.yetenek.val1.desc": "Systematic process for selecting the right talent",
    "danis.yetenek.val2.title": "Competency Model",
    "danis.yetenek.val2.desc": "Position-specific competency framework",
    "danis.yetenek.val3.title": "Talent Pool",
    "danis.yetenek.val3.desc": "Sustainable talent pipeline",
    "danis.yetenek.val4.title": "Career Development",
    "danis.yetenek.val4.desc": "Career pathways supporting employee growth",
}

def update_json(filepath, new_keys):
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    added = []
    for k, v in new_keys.items():
        if k not in data:
            data[k] = v
            added.append(k)
        else:
            print(f"  SKIP (exists): {k}")
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Added {len(added)} keys to {filepath}")
    for k in added:
        print(f"  + {k}")

update_json('locales/tr.json', TR_NEW_KEYS)
print()
update_json('locales/en.json', EN_NEW_KEYS)
